# -*- coding: utf-8 -*-
"""yuvan(harvard )

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N47SscHq1nRFbefRALiEVjnjqmTvfLSH
"""

import requests


API_KEY = "f323a341-7fdc-497d-824f-fa94ff424e62"

url = "https://api.harvardartmuseums.org/classification"

params = {
    "apikey":API_KEY,
    "size":100
}

response = requests.get(url,params=params)
response

datas=response.json()
datas

#records for objectcount more than 2500
for i in datas["records"]:
  if i["objectcount"] >= 2500:
   print ( i["name"],"-" ,i["objectcount"] )

API_key = "f323a341-7fdc-497d-824f-fa94ff424e62"
url = "https://api.harvardartmuseums.org/object"

my_divisions = ["Prints","Fragments","Seals"]

all_records = []

for division_name in my_divisions:
    for page in range(1, 26):
        params = {
            "apikey": API_key,
            "size": 100,
            "page": page,
            "division": division_name
        }

        response = requests.get(url, params=params)
        data = response.json()

        if "records" in data:
            for record in data["records"]:
                record["division"] = division_name
                all_records.append(record)

        if data.get("info", {}).get("next") is None:
            break

# Print all records
for record in all_records:
    print(record)

len(all_records)

all_md = []
all_media = []
all_colors = []

for record in all_records:
    # Metadata
    all_md.append({
        "object_id": record.get("id"),
        "title": record.get("title"),
        "culture": record.get("culture"),
        "period": record.get("period"),
        "century": record.get("century"),
        "medium": record.get("medium"),
        "dimension": record.get("height"),
        "description": record.get("description"),
        "department": record.get("department"),
        "classification": record.get("classification"),
        "accessionyear": record.get("accessionyear"),
        "accessionmethod": record.get("accessionmethod")
    })

    # Media
    all_media.append({
        "object_id": record.get("id"),
        "imagecount": record.get("imagecount"),
        "metacount": record.get("metacount"),
        "colourcount": record.get("colourcount"),
        "rank": record.get("rank"),
        "datebegin": record.get("datebegin"),
        "dateend": record.get("dateend")
    })

    # Colors
    color_details = record.get("colors")
    if color_details and isinstance(color_details, list):
        for color_item in color_details:
            all_colors.append({
                "object_id": record.get("id"),
                "colour": color_item.get("colour"),
                "spectrum": color_item.get("spectrum"),
                "hue": color_item.get("hue"),
                "percent": color_item.get("percent"),
                "css3": color_item.get("css3")
            })

len(all_colors)

len(all_media)

all_md

len(all_md)

import pandas as pd

df_md1 = pd.DataFrame(all_md)
df_media1 = pd.DataFrame(all_media)
df_colors1 = pd.DataFrame(all_colors)

df_media1

df_md = df_md1.rename(columns={
    "object_id": "id",
    "dimension": "dimensions"

})

df_media = df_media1.rename(columns={
    "object_id": "objectid",
    "metacount": "mediacount",
    "colourcount": "colorcount",
    "rank": "rank_d"

})

df_colors = df_colors1.rename(columns={
    "object_id": "objectid",
    "colour": "color"
})

print(df_md.columns)
print(df_media.columns)
print(df_colors.columns)

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cat << 'EOF' > /content/tidb-ca.pem
# -----BEGIN CERTIFICATE-----
# MIIFazCCA1OgAwIBAgIRAIIQz7DSQONZRGPgu2OCiwAwDQYJKoZIhvcNAQELBQAw
# TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
# cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMTUwNjA0MTEwNDM4
# WhcNMzUwNjA0MTEwNDM4WjBPMQswCQYDVQQGEwJVUzEpMCcGA1UEChMgSW50ZXJu
# ZXQgU2VjdXJpdHkgUmVzZWFyY2ggR3JvdXAxFTATBgNVBAMTDElTUkcgUm9vdCBY
# MTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAK3oJHP0FDfzm54rVygc
# h77ct984kIxuPOZXoHj3dcKi/vVqbvYATyjb3miGbESTtrFj/RQSa78f0uoxmyF+
# 0TM8ukj13Xnfs7j/EvEhmkvBioZxaUpmZmyPfjxwv60pIgbz5MDmgK7iS4+3mX6U
# A5/TR5d8mUgjU+g4rk8Kb4Mu0UlXjIB0ttov0DiNewNwIRt18jA8+o+u3dpjq+sW
# T8KOEUt+zwvo/7V3LvSye0rgTBIlDHCNAymg4VMk7BPZ7hm/ELNKjD+Jo2FR3qyH
# B5T0Y3HsLuJvW5iB4YlcNHlsdu87kGJ55tukmi8mxdAQ4Q7e2RCOFvu396j3x+UC
# B5iPNgiV5+I3lg02dZ77DnKxHZu8A/lJBdiB3QW0KtZB6awBdpUKD9jf1b0SHzUv
# KBds0pjBqAlkd25HN7rOrFleaJ1/ctaJxQZBKT5ZPt0m9STJEadao0xAH0ahmbWn
# OlFuhjuefXKnEgV4We0+UXgVCwOPjdAvBbI+e0ocS3MFEvzG6uBQE3xDk3SzynTn
# jh8BCNAw1FtxNrQHusEwMFxIt4I7mKZ9YIqioymCzLq9gwQbooMDQaHWBfEbwrbw
# qHyGO0aoSCqI3Haadr8faqU9GY/rOPNk3sgrDQoo//fb4hVC1CLQJ13hef4Y53CI
# rU7m2Ys6xt0nUW7/vGT1M0NPAgMBAAGjQjBAMA4GA1UdDwEB/wQEAwIBBjAPBgNV
# HRMBAf8EBTADAQH/MB0GA1UdDgQWBBR5tFnme7bl5AFzgAiIyBpY9umbbjANBgkq
# hkiG9w0BAQsFAAOCAgEAVR9YqbyyqFDQDLHYGmkgJykIrGF1XIpu+ILlaS/V9lZL
# ubhzEFnTIZd+50xx+7LSYK05qAvqFyFWhfFQDlnrzuBZ6brJFe+GnY+EgPbk6ZGQ
# 3BebYhtF8GaV0nxvwuo77x/Py9auJ/GpsMiu/X1+mvoiBOv/2X/qkSsisRcOj/KK
# NFtY2PwByVS5uCbMiogziUwthDyC3+6WVwW6LLv3xLfHTjuCvjHIInNzktHCgKQ5
# ORAzI4JMPJ+GslWYHb4phowim57iaztXOoJwTdwJx4nLCgdNbOhdjsnvzqvHu7Ur
# TkXWStAmzOVyyghqpZXjFaH3pO3JLF+l+/+sKAIuvtd7u+Nxe5AW0wdeRlN8NwdC
# jNPElpzVmbUq4JUagEiuTDkHzsxHpFKVK7q4+63SM1N95R1NbdWhscdCb+ZAJzVc
# oyi3B43njTOQ5yOf+1CceWxG1bQVs5ZufpsMljq4Ui0/1lvh+wjChP4kqKOJ2qxq
# 4RgqsahDYVvTH9w7jXbyLeiNdd8XM2w9U/t7y0Ff/9yi0GE44Za4rF2LN9d11TPA
# mRGunUHBcnWEvgJBQl9nJEiU0Zsnvgc/ubhPgXRR4Xq37Z0j4r7g1SgEEzwxA57d
# emyPxgcYxn/eR44/KJ4EBs+lVDR3veyJm+kXQ99b21/+jh5Xos1AnX5iItreGCc=
# -----END CERTIFICATE-----
# EOF

!ls -l /content/tidb-ca.pem

!pip install sqlalchemy pymysql pandas --quiet
from sqlalchemy import create_engine, text
from google.colab import files


USERNAME = "dBhZC2DneRLFSw9.root"
PASSWORD = "cDwphfnAjgb810t1"
HOST = "gateway01.ap-southeast-1.prod.aws.tidbcloud.com"
DATABASE_NAME = "Harward_Data"
CA_PATH = "/content/tidb-ca.pem"

engine = create_engine(
    f"mysql+pymysql://{USERNAME}:{PASSWORD}@{HOST}:4000/{DATABASE_NAME}",
    connect_args={
        "ssl": {"ca": CA_PATH}
    },
    pool_pre_ping=True
)

with engine.connect() as conn:
    print(conn.execute(text("SELECT 1")).fetchone())

from sqlalchemy import text

with engine.begin() as conn:  # automatically commits

    conn.execute(text("""
        CREATE TABLE IF NOT EXISTS artifacts_metadata (
            id INT PRIMARY KEY,
            title TEXT,
            culture TEXT,
            period TEXT,
            century TEXT,
            medium TEXT,
            dimensions TEXT,
            description TEXT,
            department TEXT,
            classification TEXT,
            accessionyear INT,
            accessionmethod TEXT
        );
    """))

    conn.execute(text("""
        CREATE TABLE IF NOT EXISTS artifacts_media (
            objectid INT,
            imagecount INT,
            mediacount INT,
            colorcount INT,
            rank_d INT,
            datebegin INT,
            dateend INT,
            FOREIGN KEY (objectid) REFERENCES artifacts_metadata(id)
        );
    """))

    conn.execute(text("""
        CREATE TABLE IF NOT EXISTS artifacts_colors (
            objectid INT,
            color TEXT,
            spectrum TEXT,
            hue TEXT,
            percent REAL,
            css3 TEXT,
            FOREIGN KEY (objectid) REFERENCES artifacts_metadata(id)
        );
    """))

print("Tables created successfully")

with engine.begin() as conn:
    result = conn.execute(text("SHOW TABLES"))
    tables = [row[0] for row in result]

print(tables)

df_md = df_md.drop_duplicates(subset="id", keep="first")

df_media = df_media[df_media["objectid"].isin(df_md["id"])]
df_colors = df_colors[df_colors["objectid"].isin(df_md["id"])]

df_md.to_sql(
    "artifacts_metadata",
    engine,
    if_exists="append",
    index=False
)

df_media.to_sql(
    "artifacts_media",
    engine,
    if_exists="append",
    index=False
)

df_colors.to_sql(
    "artifacts_colors",
    engine,
    if_exists="append",
    index=False
)

print("Data inserted successfully")

print("metadata rows:", len(df_md))
print("media rows:", len(df_media))
print("colors rows:", len(df_colors))

